// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upizkgzacsttdswtgpsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaXprZ3phY3N0dGRzd3RncHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Njg1OTUsImV4cCI6MjA3MzA0NDU5NX0.PtTzv4iS7EcUwfBdsBWjMBRBWnJgYBYdPRrJRq_eDNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});